version: '3'

services:
  web:
    image: django-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  # Add other services like Redis, Celery, etc., if needed

  # Uncomment the following if you want to use Redis with Celery
  # redis:
  #   image: redis:latest

  # Uncomment the following if you want to use Celery
  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-celery
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - redis
  #     - web
